# Generated by Django 5.1.5 on 2025-02-12 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0004_obra_imagenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoLimpio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('metros_cuadrados', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Metros Cuadrados')),
                ('estructura', models.CharField(max_length=200, verbose_name='Estructura')),
                ('tipo_contenedor', models.CharField(max_length=200, verbose_name='Tipo de Contenedor')),
                ('puntaje', models.IntegerField(verbose_name='Puntaje')),
                ('señaletica', models.BooleanField(default=True, verbose_name='Señalética')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('clasificacion', models.CharField(max_length=100, verbose_name='Clasificación')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_limpios', to='obras.obra')),
            ],
        ),
    ]
