# Generated by Django 5.1.5 on 2025-02-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntolimpio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntolimpio',
            name='clasificacion',
            field=models.CharField(choices=[('correcta', 'Correcta'), ('a_mejorar', 'A Mejorar'), ('incorrecta', 'Incorrecta'), ('no_aplica', 'No Aplica')], max_length=20, verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='puntolimpio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
