# Generated by Django 5.1.5 on 2025-02-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntolimpio', '0002_alter_puntolimpio_clasificacion_alter_puntolimpio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntolimpio',
            name='accesibilidad',
            field=models.CharField(choices=[('en_planta_baja', 'En Planta Baja'), ('en_pisos', 'En Pisos')], default='en_planta_baja', max_length=20, verbose_name='Accesibilidad'),
        ),
    ]
