# Generated by Django 5.1.5 on 2025-02-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntolimpio', '0003_puntolimpio_accesibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntolimpio',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='puntolimpio',
            name='clasificacion',
            field=models.CharField(choices=[('correcta', 'Correcta'), ('a_mejorar', 'A Mejorar'), ('incorrecta', 'Incorrecta'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=20, verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='puntolimpio',
            name='estructura',
            field=models.CharField(default='No especificado', max_length=200, verbose_name='Estructura'),
        ),
        migrations.AlterField(
            model_name='puntolimpio',
            name='metros_cuadrados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Metros Cuadrados'),
        ),
        migrations.AlterField(
            model_name='puntolimpio',
            name='observaciones',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='puntolimpio',
            name='puntaje',
            field=models.IntegerField(default=0, verbose_name='Puntaje'),
        ),
        migrations.AlterField(
            model_name='puntolimpio',
            name='tipo_contenedor',
            field=models.CharField(default='No especificado', max_length=200, verbose_name='Tipo de Contenedor'),
        ),
        migrations.AlterField(
            model_name='puntolimpio',
            name='ubicacion',
            field=models.CharField(default='No especificado', max_length=200, verbose_name='Ubicación'),
        ),
    ]
