# Generated by Django 5.1.5 on 2025-02-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puntolimpio', '0004_alter_puntolimpio_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntolimpio',
            name='cantidad',
        ),
    ]
