# Generated by Django 5.1.6 on 2025-02-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntolimpio', '0005_remove_puntolimpio_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntolimpio',
            name='estado',
            field=models.TextField(default='activo', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='puntolimpio',
            name='puntaje',
            field=models.IntegerField(default=0, null=True, verbose_name='Puntaje'),
        ),
    ]
