# Generated by Django 5.1.5 on 2025-03-02 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0006_remove_obra_localidad_barrio_and_more'),
        ('puntolimpio', '0006_puntolimpio_estado_alter_puntolimpio_puntaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoAcopio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(default='No especificado', max_length=200, verbose_name='Ubicación')),
                ('accesibilidad', models.CharField(choices=[('en_planta_baja', 'En Planta Baja'), ('en_pisos', 'En Pisos')], default='en_planta_baja', max_length=20, verbose_name='Accesibilidad')),
                ('metros_cuadrados', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Metros Cuadrados')),
                ('estructura', models.CharField(default='No especificado', max_length=200, verbose_name='Estructura')),
                ('tipo_contenedor', models.CharField(default='No especificado', max_length=200, verbose_name='Tipo de Contenedor')),
                ('puntaje', models.IntegerField(default=0, null=True, verbose_name='Puntaje')),
                ('señaletica', models.BooleanField(default=True, verbose_name='Señalética')),
                ('observaciones', models.TextField(blank=True, default='', null=True, verbose_name='Observaciones')),
                ('clasificacion', models.CharField(choices=[('correcta', 'Correcta'), ('a_mejorar', 'A Mejorar'), ('incorrecta', 'Incorrecta'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=20, verbose_name='Clasificación')),
                ('estado', models.TextField(default='activo', verbose_name='Estado')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punto_acopio', to='obras.obra')),
            ],
        ),
    ]
