# Generated by Django 5.1.6 on 2025-03-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puntolimpio', '0008_puntolimpio_fecha_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntolimpio',
            name='metros_cuadrados',
        ),
    ]
