# Generated by Django 5.1.6 on 2025-03-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puntolimpio', '0009_remove_puntolimpio_metros_cuadrados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntoacopio',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='puntoacopio',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='puntoacopio',
            name='puntaje',
        ),
        migrations.RemoveField(
            model_name='puntoacopio',
            name='señaletica',
        ),
    ]
