# Generated by Django 5.1.6 on 2025-03-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puntolimpio', '0011_puntolimpio_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntolimpio',
            name='cantidad',
        ),
    ]
