# Generated by Django 5.1.6 on 2025-03-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntolimpio', '0012_remove_puntolimpio_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoacopio',
            name='clasificacion',
            field=models.CharField(choices=[('correcta', 'Correcta'), ('a_mejorar', 'A Mejorar'), ('incorrecta', 'Incorrecta'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=20, verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='puntoacopio',
            name='observaciones',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='puntoacopio',
            name='puntaje',
            field=models.IntegerField(default=0, null=True, verbose_name='Puntaje'),
        ),
        migrations.AddField(
            model_name='puntoacopio',
            name='señaletica',
            field=models.BooleanField(default=True, verbose_name='Señalética'),
        ),
        migrations.AddField(
            model_name='puntolimpio',
            name='metros_cuadrados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Metros Cuadrados'),
        ),
    ]
