# Generated by Django 5.1.6 on 2025-03-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntolimpio', '0013_puntoacopio_clasificacion_puntoacopio_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntolimpio',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
    ]
