# Generated by Django 5.1.6 on 2025-03-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puntolimpio', '0014_puntolimpio_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntoacopio',
            name='señaletica',
        ),
        migrations.RemoveField(
            model_name='puntolimpio',
            name='señaletica',
        ),
    ]
