# Generated by Django 5.1.6 on 2025-03-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntolimpio', '0015_remove_puntoacopio_señaletica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoacopio',
            name='clasificacion',
            field=models.CharField(choices=[('correcta', 'Correcta'), ('a_mejorar', 'A Mejorar'), ('incorrecta', 'Incorrecta'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=20, verbose_name='Clasificacion'),
        ),
        migrations.AlterField(
            model_name='puntoacopio',
            name='ubicacion',
            field=models.CharField(default='No especificado', max_length=200, verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='puntolimpio',
            name='clasificacion',
            field=models.CharField(choices=[('correcta', 'Correcta'), ('a_mejorar', 'A Mejorar'), ('incorrecta', 'Incorrecta'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=20, verbose_name='Clasificacion'),
        ),
        migrations.AlterField(
            model_name='puntolimpio',
            name='ubicacion',
            field=models.CharField(default='No especificado', max_length=200, verbose_name='Ubicacion'),
        ),
    ]
