# Generated by Django 5.1.5 on 2025-02-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('super_administrador', 'Super Administrador'), ('coordinador_obra', 'Coordinador de Obra'), ('futuro_cliente', 'Futuro Cliente'), ('coordinador_retiro', 'Coordinador de Retiro'), ('supervisor_obra', 'Supervisor de Obra'), ('tecnico', 'Técnico'), ('cliente', 'Cliente')], max_length=50),
        ),
    ]
