# Generated by Django 5.1.5 on 2025-02-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('super_administrador', 'Super Administrador'), ('coordinador_obra', 'Coordinador de Obra'), ('coordinador_retiro', 'Coordinador de Retiro'), ('supervisor_obra', 'Supervisor de Obra'), ('tecnico', 'Técnico')], max_length=50),
        ),
    ]
