# Generated by Django 5.1.5 on 2025-02-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('super_administrador', 'Super Administrador'), ('coordinador_obra', 'Coordinador de Obra'), ('coordinador_logistico', 'Coordinador Logistico'), ('supervisor_obra', 'Supervisor de Obra'), ('tecnico', 'Técnico'), ('cliente', 'Cliente')], max_length=50),
        ),
    ]
