# Generated by Django 5.1.6 on 2025-03-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('coordinador', 'Coordinador de Obra'), ('coordinadorlogistico', 'Coordinador Logistico'), ('supervisor', 'Supervisor de Obra'), ('tecnico', 'Técnico'), ('cliente', 'Cliente')], max_length=50),
        ),
    ]
