# Generated by Django 5.1.5 on 2025-02-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportista',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
            preserve_default=False,
        ),
    ]
