# Generated by Django 5.1.5 on 2025-02-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportistas', '0002_transportista_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
