# Generated by Django 5.1.5 on 2025-02-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor_obra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorobra',
            name='nivel_capacitacion',
            field=models.CharField(choices=[('participa_activamente', 'Participa Activamente'), ('participa_pero_puede_mejorar', 'Participa Pero Puede Mejorar'), ('poca_participacion', 'Poca Participacion'), ('falta_mayor_participacion', 'Falta Mayor Participacion'), ('no_participa', 'No Participa'), ('no_hay', 'No Hay')], default='No Hay', max_length=50),
        ),
    ]
