# Generated by Django 5.1.5 on 2025-02-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor_obra', '0003_supervisorobra_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorobra',
            name='rol',
        ),
    ]
