# Generated by Django 5.1.6 on 2025-03-01 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor_obra', '0004_remove_supervisorobra_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorobra',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supervisorobra',
            name='nombre',
        ),
        migrations.AddField(
            model_name='supervisorobra',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisorobra',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supervisorobra',
            name='nivel_capacitacion',
            field=models.CharField(choices=[('participa_activamente', 'Participa Activamente'), ('participa_pero_puede_mejorar', 'Participa Pero Puede Mejorar'), ('poca_participacion', 'Poca Participacion'), ('falta_mayor_participacion', 'Falta Mayor Participacion'), ('no_participa', 'No Participa'), ('no_hay', 'No Hay')], default='no_hay', max_length=50),
        ),
    ]
