# Generated by Django 5.1.6 on 2025-03-07 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0010_remove_obra_cronograma_obra_archivo_and_more'),
        ('supervisor_obra', '0005_remove_supervisorobra_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorobra',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisores', to='obras.obra'),
        ),
    ]
