# Generated by Django 5.1.6 on 2025-03-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_gestoras', '0002_alter_empresagestora_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresagestora',
            name='tipo_material',
            field=models.CharField(choices=[('escombro_limpio', 'Escombro Limpio'), ('plastico', 'Plástico'), ('papel_carton', 'Papel y Cartón'), ('metales', 'Metales'), ('madera', 'Madera'), ('mezclados', 'Mezclados'), ('peligrosos', 'Peligrosos')], default='plastico', max_length=20),
        ),
    ]
