# Generated by Django 5.1.6 on 2025-03-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_gestoras', '0003_empresagestora_tipo_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresagestora',
            name='tipo_material',
            field=models.CharField(choices=[('escombro_limpio', 'Escombro Limpio'), ('plastico', 'Plástico'), ('papel_carton', 'Papel y Carton'), ('metales', 'Metales'), ('madera', 'Madera'), ('mezclados', 'Mezclados'), ('peligrosos', 'Peligrosos')], default='plastico', max_length=20),
        ),
    ]
