# Generated by Django 5.1.5 on 2025-02-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=300)),
                ('contacto', models.CharField(max_length=50)),
                ('nombre_contacto', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('razon_social', models.CharField(max_length=300)),
                ('direccion_fiscal', models.CharField(max_length=300)),
                ('rut', models.CharField(max_length=300)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('cronograma', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
