# Generated by Django 5.1.5 on 2025-02-05 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_solicitudcliente_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='solicitudcliente',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='solicitud', serialize=False, to='clientes.cliente'),
        ),
    ]
