# Generated by Django 5.1.5 on 2025-02-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_solicitudcliente_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cronograma',
        ),
    ]
