# Generated by Django 5.1.5 on 2025-02-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='No Especificado', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rol',
            field=models.CharField(default='cliente', editable=False, max_length=20),
        ),
    ]
