# Generated by Django 5.1.6 on 2025-03-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_remove_cliente_mail_remove_cliente_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcliente',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('terminado', 'Terminado')], default='pendiente', max_length=10),
        ),
    ]
