# Generated by Django 5.1.5 on 2025-02-17 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas_gestoras', '0002_alter_empresagestora_id'),
        ('obras', '0004_obra_imagenes'),
        ('transportistas', '0003_alter_transportista_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinacionRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_retiro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Retiro')),
                ('pesaje', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pesaje')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('tipo_material', models.CharField(choices=[('escombro_limpio', 'Escombro Limpio'), ('plastico', 'Plástico'), ('papel_carton', 'Papel y Cartón'), ('metales', 'Metales'), ('madera', 'Madera'), ('mezclados', 'Mezclados'), ('peligrosos', 'Peligrosos')], max_length=20, verbose_name='Tipo de Material')),
                ('empresa_tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinaciones_retiro', to='empresas_gestoras.empresagestora', verbose_name='Empresa de Tratamiento')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinaciones_retiro', to='obras.obra', verbose_name='Obra')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinaciones_retiro', to='transportistas.transportista', verbose_name='Transportista')),
            ],
        ),
    ]
