# Generated by Django 5.1.5 on 2025-02-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacionretiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinacionretiro',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
