# Generated by Django 5.1.5 on 2025-02-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacionretiro', '0002_alter_coordinacionretiro_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinacionretiro',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('inactivo', 'Inactivo')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
