# Generated by Django 5.1.6 on 2025-03-06 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacionretiro', '0003_alter_coordinacionretiro_estado'),
        ('empresas_gestoras', '0002_alter_empresagestora_id'),
        ('transportistas', '0003_alter_transportista_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinacionretiro',
            name='empresa_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinaciones_retiro', to='empresas_gestoras.empresagestora', verbose_name='Empresa de Tratamiento'),
        ),
        migrations.AlterField(
            model_name='coordinacionretiro',
            name='estado',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('inactivo', 'Inactivo')], default='pendiente', max_length=20, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='coordinacionretiro',
            name='transportista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinaciones_retiro', to='transportistas.transportista', verbose_name='Transportista'),
        ),
    ]
