# Generated by Django 5.1.6 on 2025-03-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacionretiro', '0004_alter_coordinacionretiro_empresa_tratamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinacionretiro',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad'),
        ),
    ]
