# Generated by Django 5.1.6 on 2025-03-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinacionretiro', '0005_coordinacionretiro_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinacionretiro',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='coordinacionretiro',
            name='tipo_material',
            field=models.CharField(choices=[('escombro_limpio', 'Escombro Limpio'), ('plastico', 'Plástico'), ('papel_carton', 'Papel y Carton'), ('metales', 'Metales'), ('madera', 'Madera'), ('mezclados', 'Mezclados'), ('peligrosos', 'Peligrosos')], max_length=20, verbose_name='Tipo de Material'),
        ),
    ]
