# Generated by Django 5.1.5 on 2025-02-17 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0004_obra_imagenes'),
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Capacitacion')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='obras.obra', verbose_name='Obra')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='tecnicos.tecnico', verbose_name='Técnico')),
            ],
        ),
    ]
