# Generated by Django 5.1.6 on 2025-03-06 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0002_alter_capacitacion_id'),
        ('supervisor_obra', '0005_remove_supervisorobra_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='supervisor_obra.supervisorobra', verbose_name='Supervisor'),
        ),
    ]
