# Generated by Django 5.1.6 on 2025-03-07 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0004_alter_capacitacion_supervisor'),
        ('supervisor_obra', '0006_alter_supervisorobra_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervisor_obra.supervisorobra'),
        ),
    ]
