# Generated by Django 5.1.5 on 2025-02-12 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puntolimpio', '0002_alter_puntolimpio_clasificacion_alter_puntolimpio_id'),
        ('transportistas', '0003_alter_transportista_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('proteccion', models.CharField(max_length=200, verbose_name='Protección')),
                ('tipo_contenedor', models.CharField(max_length=200, verbose_name='Tipo de Contenedor')),
                ('estado_del_contenedor', models.CharField(max_length=200, verbose_name='Estado del Contenedor')),
                ('esta_lleno', models.BooleanField(default=False, verbose_name='Está lleno')),
                ('tipo_material', models.CharField(choices=[('escombro_limpio', 'Escombro Limpio'), ('plastico', 'Plástico'), ('papel_carton', 'Papel y Cartón'), ('metales', 'Metales'), ('madera', 'Madera'), ('mezclados', 'Mezclados'), ('peligrosos', 'Peligrosos')], max_length=20, verbose_name='Tipo de Material')),
                ('ventilacion', models.CharField(blank=True, help_text="Obligatorio si el material es 'peligrosos'", max_length=100, null=True, verbose_name='Ventilación')),
                ('punto_limpio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='puntolimpio.puntolimpio', verbose_name='Punto Limpio')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='transportistas.transportista', verbose_name='Transportista')),
            ],
        ),
    ]
