# Generated by Django 5.1.6 on 2025-03-03 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_material_obra'),
        ('transportistas', '0003_alter_transportista_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='transportista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='transportistas.transportista', verbose_name='Transportista'),
        ),
    ]
