# Generated by Django 5.1.6 on 2025-03-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0005_material_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='material',
            name='proteccion',
            field=models.CharField(max_length=200, verbose_name='Proteccion'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo_material',
            field=models.CharField(choices=[('escombro_limpio', 'Escombro Limpio'), ('plastico', 'Plástico'), ('papel_carton', 'Papel y Carton'), ('metales', 'Metales'), ('madera', 'Madera'), ('mezclados', 'Mezclados'), ('peligrosos', 'Peligrosos')], max_length=20, verbose_name='Tipo de Material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='ventilacion',
            field=models.CharField(blank=True, help_text="Obligatorio si el material es 'peligrosos'", max_length=100, null=True, verbose_name='Ventilacion'),
        ),
    ]
