# Generated by Django 5.1.5 on 2025-02-05 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_remove_solicitudcliente_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('metros_cuadrados', models.DecimalField(decimal_places=3, max_digits=10)),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='obras/imagenes/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='clientes.cliente')),
            ],
        ),
    ]
