# Generated by Django 5.1.5 on 2025-02-05 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudObra',
            fields=[
                ('obra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='solicitud', serialize=False, to='obras.obra')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
