# Generated by Django 5.1.5 on 2025-02-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_solicitudobra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='imagenes',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='metros_cuadrados',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='nombre',
        ),
        migrations.AddField(
            model_name='obra',
            name='cant_pisos',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Pisos'),
        ),
        migrations.AddField(
            model_name='obra',
            name='cant_visitas_mes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Visitas al Mes'),
        ),
        migrations.AddField(
            model_name='obra',
            name='duracion_obra',
            field=models.CharField(blank=True, default='No especificado', max_length=100, null=True, verbose_name='Duración de Obra'),
        ),
        migrations.AddField(
            model_name='obra',
            name='etapa_obra',
            field=models.CharField(blank=True, default='No especificado', max_length=100, null=True, verbose_name='Etapa de Obra'),
        ),
        migrations.AddField(
            model_name='obra',
            name='inicio_obra',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de Obra'),
        ),
        migrations.AddField(
            model_name='obra',
            name='localidad_barrio',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Localidad / Barrio'),
        ),
        migrations.AddField(
            model_name='obra',
            name='m2_obra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='M2 Obra'),
        ),
        migrations.AddField(
            model_name='obra',
            name='mail_telefono_capataz',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Mail y Teléfono Capataz'),
        ),
        migrations.AddField(
            model_name='obra',
            name='mail_telefono_encargado_supervisor',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Mail y Teléfono del Encargado de Supervisor Ambiental'),
        ),
        migrations.AddField(
            model_name='obra',
            name='mail_telefono_jefe_obra',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Mail y Teléfono Jefe de Obra'),
        ),
        migrations.AddField(
            model_name='obra',
            name='nombre_capataz',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Nombre Capataz'),
        ),
        migrations.AddField(
            model_name='obra',
            name='nombre_constructora',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Nombre de Constructora'),
        ),
        migrations.AddField(
            model_name='obra',
            name='nombre_encargado_supervisor',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Nombre Encargado de Supervisor Ambiental'),
        ),
        migrations.AddField(
            model_name='obra',
            name='nombre_jefe_obra',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Nombre Jefe de Obra'),
        ),
        migrations.AddField(
            model_name='obra',
            name='nombre_obra',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Nombre de Obra'),
        ),
        migrations.AddField(
            model_name='obra',
            name='pedido',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='direccion',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Dirección'),
        ),
    ]
