# Generated by Django 5.1.5 on 2025-02-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_remove_obra_imagenes_remove_obra_metros_cuadrados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='obras/imagenes/'),
        ),
    ]
