# Generated by Django 5.1.5 on 2025-02-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0004_obra_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='cronograma',
            field=models.TextField(default='No especificado'),
            preserve_default=False,
        ),
    ]
