# Generated by Django 5.1.5 on 2025-02-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0005_obra_cronograma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='localidad_barrio',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='mail_telefono_capataz',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='mail_telefono_encargado_supervisor',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='mail_telefono_jefe_obra',
        ),
        migrations.AddField(
            model_name='obra',
            name='barrio',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='obra',
            name='localidad',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='obra',
            name='mail_capataz',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Mail Capataz'),
        ),
        migrations.AddField(
            model_name='obra',
            name='mail_encargado_supervisor',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Mail Encargado de Supervisor Ambiental'),
        ),
        migrations.AddField(
            model_name='obra',
            name='mail_jefe_obra',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Mail Jefe de Obra'),
        ),
        migrations.AddField(
            model_name='obra',
            name='telefono_capataz',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Teléfono Capataz'),
        ),
        migrations.AddField(
            model_name='obra',
            name='telefono_encargado_supervisor',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Teléfono del Encargado de Supervisor Ambiental'),
        ),
        migrations.AddField(
            model_name='obra',
            name='telefono_jefe_obra',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Teléfono Jefe de Obra'),
        ),
    ]
