# Generated by Django 5.1.6 on 2025-03-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0006_remove_obra_localidad_barrio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudobra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('terminado', 'Terminado')], default='pendiente', max_length=10),
        ),
    ]
