# Generated by Django 5.1.6 on 2025-03-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0007_alter_solicitudobra_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='imagenes',
        ),
    ]
