# Generated by Django 5.1.6 on 2025-03-06 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0008_remove_obra_imagenes'),
        ('tecnicos', '0004_tecnico_usuario_alter_tecnico_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras', to='tecnicos.tecnico'),
        ),
    ]
