# Generated by Django 5.1.6 on 2025-03-07 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0009_obra_tecnico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='cronograma',
        ),
        migrations.AddField(
            model_name='obra',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='obras/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xls', 'xlsx'])], verbose_name='Archivo Adjunto'),
        ),
        migrations.AddField(
            model_name='obra',
            name='tipo_construccion',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Tipo de Construccion'),
        ),
    ]
