# Generated by Django 5.1.6 on 2025-03-07 19:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0010_remove_obra_cronograma_obra_archivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='archivo',
        ),
        migrations.CreateModel(
            name='ArchivoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='obras/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xls', 'xlsx'])], verbose_name='Archivo Adjunto')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='obras.obra')),
            ],
        ),
    ]
