# Generated by Django 5.1.6 on 2025-03-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0011_remove_obra_archivo_archivoobra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='direccion',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='duracion_obra',
            field=models.CharField(blank=True, default='No especificado', max_length=100, null=True, verbose_name='Duracion de Obra'),
        ),
    ]
