# Generated by Django 5.1.5 on 2025-02-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornal_ambiental', models.TextField()),
                ('operarios', models.TextField()),
                ('oficina_tecnica', models.TextField()),
                ('participantes_de_obra_observaciones', models.TextField()),
                ('limpieza_general_por_terreno', models.TextField()),
                ('limpieza_general_por_pisos', models.TextField()),
                ('limpieza_general_observaciones', models.TextField()),
                ('logistica_de_obra', models.TextField()),
                ('logistica_de_obra_observaciones', models.TextField()),
            ],
        ),
    ]
