# Generated by Django 5.1.5 on 2025-02-17 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condiciondeobras', '0001_initial'),
        ('obras', '0004_obra_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='condiciondeobra',
            name='obra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_de_obra', to='obras.obra'),
            preserve_default=False,
        ),
    ]
