# Generated by Django 5.1.5 on 2025-02-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='acciones_tomadas',
            field=models.TextField(blank=True, null=True, verbose_name='Acciones tomadas'),
        ),
    ]
