# Generated by Django 5.1.5 on 2025-02-17 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion_server', models.CharField(max_length=200)),
                ('tipo_imagen', models.CharField(max_length=200)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='visitas.visita')),
            ],
        ),
    ]
