# Generated by Django 5.1.6 on 2025-03-04 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0002_remove_fotos_tipo_imagen_and_more'),
        ('obras', '0008_remove_obra_imagenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='obras/imagenes/')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_set', to='obras.obra')),
            ],
        ),
        migrations.DeleteModel(
            name='Fotos',
        ),
    ]
