# Generated by Django 5.1.6 on 2025-03-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0004_rename_obraimagen_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
    ]
