# Generated by Django 5.1.5 on 2025-02-22 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0006_remove_obra_localidad_barrio_and_more'),
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formularios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('motivo_de_visita', models.CharField(max_length=200, verbose_name='Motivo de visita')),
                ('otro_motivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Otro motivo')),
                ('participante_jornal_ambiental', models.CharField(max_length=200, verbose_name='Participante jornal ambiental')),
                ('participante_operario', models.CharField(max_length=200, verbose_name='Participante jornal ambiental')),
                ('participante_oficina_tecnica', models.CharField(max_length=200, verbose_name='Participante jornal ambiental')),
                ('participante_observaciones', models.CharField(max_length=500, verbose_name='Participante jornal ambiental')),
                ('limpieza_general_en_terreno', models.CharField(max_length=200, verbose_name='Limpieza general en terreno')),
                ('limpieza_general_en_pisos', models.CharField(max_length=200, verbose_name='Limpieza general en terreno')),
                ('limpieza_general_observaciones', models.CharField(max_length=500, verbose_name='Limpieza general en terreno')),
                ('logistica_de_obra', models.CharField(max_length=200, verbose_name='Logística de obra')),
                ('logistica_de_obra_observaciones', models.CharField(max_length=500, verbose_name='Logística de obra')),
                ('punto_limpio', models.CharField(choices=[('si_hay', 'Sí Hay'), ('no_hay', 'No Hay')], max_length=200, verbose_name='Punto limpio')),
                ('punto_limpio_ubicacion', models.CharField(max_length=200, verbose_name='Punto limpio ubicación')),
                ('punto_limpio_estructura', models.CharField(max_length=200, verbose_name='Punto limpio ubicación')),
                ('punto_limpio_tipo_contenedor', models.CharField(max_length=200, verbose_name='Punto limpio ubicación')),
                ('punto_limpio_estado_contenedor', models.CharField(max_length=200, verbose_name='Punto limpio ubicación')),
                ('punto_limpio_señaletica', models.CharField(max_length=200, verbose_name='Punto limpio ubicación')),
                ('punto_limpio_observaciones', models.CharField(max_length=500, verbose_name='Punto limpio ubicación')),
                ('puntos_limpios_por_pisos', models.CharField(choices=[('si_hay', 'Sí Hay'), ('no_hay', 'No Hay')], max_length=200, verbose_name='Puntos limpios por pisos')),
                ('punto_limpio_pisos', models.CharField(choices=[('si_hay', 'Sí Hay'), ('no_hay', 'No Hay')], max_length=200, verbose_name='Punto limpio')),
                ('punto_limpio_ubicacion_pisos', models.CharField(max_length=200, verbose_name='Punto limpio ubicación')),
                ('punto_limpio_estructura_pisos', models.CharField(max_length=200, verbose_name='Punto limpio ubicación')),
                ('punto_limpio_tipo_contenedor_pisos', models.CharField(max_length=200, verbose_name='Punto limpio ubicación')),
                ('punto_limpio_estado_contenedor_pisos', models.CharField(max_length=200, verbose_name='Punto limpio ubicación')),
                ('punto_limpio_señaletica_pisos', models.CharField(max_length=200, verbose_name='Punto limpio ubicación')),
                ('punto_limpio_observaciones_pisos', models.CharField(max_length=500, verbose_name='Punto limpio ubicación')),
                ('punto_de_acopio_ubicacion', models.CharField(choices=[('si_hay', 'Sí Hay'), ('no_hay', 'No Hay')], max_length=200, verbose_name='Punto de acopio')),
                ('punto_de_acopio_estructura', models.CharField(choices=[('si_hay', 'Sí Hay'), ('no_hay', 'No Hay')], max_length=200, verbose_name='Punto de acopio')),
                ('punto_de_acopio_tipo_contenedor', models.CharField(choices=[('si_hay', 'Sí Hay'), ('no_hay', 'No Hay')], max_length=200, verbose_name='Punto de acopio')),
                ('punto_de_acopio_estado_contenedor', models.CharField(choices=[('si_hay', 'Sí Hay'), ('no_hay', 'No Hay')], max_length=200, verbose_name='Punto de acopio')),
                ('punto_de_acopio_señaletica', models.CharField(choices=[('si_hay', 'Sí Hay'), ('no_hay', 'No Hay')], max_length=200, verbose_name='Punto de acopio')),
                ('punto_de_acopio_observaciones', models.CharField(choices=[('si_hay', 'Sí Hay'), ('no_hay', 'No Hay')], max_length=500, verbose_name='Punto de acopio')),
                ('acciones_tomadas', models.CharField(max_length=500, verbose_name='Acciones tomadas')),
                ('otras_observaciones', models.CharField(max_length=500, verbose_name='Otras observaciones')),
                ('escombro_limpio', models.CharField(choices=[('aplica', 'Aplica'), ('no_aplica', 'No Aplica')], max_length=200, verbose_name='Escombro limpio')),
                ('escombro_limpio_observaciones', models.CharField(choices=[('acopio_a_granel', 'Acopio a granel'), ('en_volquetas', 'En volquetas'), ('en_bolson_azul', 'En bolson azul'), ('poco_accesible', 'Poco accesible'), ('vacio', 'Vacio'), ('lleno', 'Lleno'), ('se_esta_reutilizando_en_obra', 'Se está reutilizando en obra'), ('contiene_resiuduos_que_no_corresponden', 'Contiene residuos que no corresponden'), ('otro', 'Otro')], max_length=500, verbose_name='Escombro limpio')),
                ('escombro_limpio_otras_observaciones', models.CharField(max_length=500, verbose_name='Escombro limpio')),
                ('plastico', models.CharField(choices=[('aplica', 'Aplica'), ('no_aplica', 'No Aplica')], max_length=200, verbose_name='Plástico')),
                ('plastico_observaciones', models.CharField(choices=[('vacio', 'Vacio'), ('lleno', 'Lleno'), ('contiene_plasticos_no_reciclables', 'Contiene plásticos no reciclables'), ('contiene_residuos_que_no_corresponden', 'Contiene residuos que no corresponden'), ('sucio_y/o_contaminado', 'Sucio y/o contaminado'), ('poca_compactacion', 'Poca compactación'), ('poco_accesible', 'Poco accesible'), ('no_esta_implementada_la_fraccion', 'No está implementada la fracción'), ('otro', 'Otro')], max_length=500, verbose_name='Plástico')),
                ('plastico_otras_observaciones', models.CharField(max_length=500, verbose_name='Plástico')),
                ('papel_y_carton', models.CharField(choices=[('aplica', 'Aplica'), ('no_aplica', 'No Aplica')], max_length=200, verbose_name='Papel y cartón')),
                ('papel_y_carton_observaciones', models.CharField(choices=[('vacio', 'Vacio'), ('lleno', 'Lleno'), ('falta_proteccion_interperie', 'Falta protección interperie'), ('contiene_residuos_que_no_corresponden', 'Contiene residuos que no corresponden'), ('sucio_y/o_contaminado', 'Sucio y/o contaminado'), ('poca_compactacion', 'Poca compactación'), ('poco_accesible', 'Poco accesible'), ('no_esta_implementada_la_fraccion', 'No está implementada la fracción'), ('otro', 'Otro')], max_length=500, verbose_name='Papel y cartón')),
                ('papel_y_carton_otras_observaciones', models.CharField(max_length=500, verbose_name='Papel y cartón')),
                ('metales', models.CharField(choices=[('aplica', 'Aplica'), ('no_aplica', 'No Aplica')], max_length=200, verbose_name='Metales')),
                ('metales_observaciones', models.CharField(choices=[('a_granel', 'A granel'), ('en_cajon_prefabricado', 'En cajón prefabricado'), ('se_utiliza_en_obra', 'Se utiliza en obra'), ('mucha_cantidad', 'Mucha cantidad'), ('poco_accesible', 'Poco accesible'), ('otro', 'Otro')], max_length=500, verbose_name='Metales')),
                ('metales_otras_observaciones', models.CharField(max_length=500, verbose_name='Metales')),
                ('madera', models.CharField(choices=[('a_granel', 'A granel'), ('mala_organizacion', 'Mala organización'), ('mucha_cantidad', 'Mucha cantidad'), ('se_esta_reutilizando_en_obra', 'Se está reutilizando en obra'), ('contaminado_con_aceite_pintura_pegamento', 'Contaminado con aceite, pintura, pegamento'), ('otro', 'Otro')], max_length=500, verbose_name='Madera')),
                ('madera_otras_observaciones', models.CharField(max_length=500, verbose_name='Madera')),
                ('mezclados', models.CharField(choices=[('aplica', 'Aplica'), ('no_aplica', 'No Aplica')], max_length=200, verbose_name='Mezclados')),
                ('mezclados_separaciones', models.CharField(max_length=200, verbose_name='Mezclados')),
                ('mezclados_observaciones', models.CharField(choices=[('presencia_de_materiales_valorizables', 'Presencia de materiales valorizables'), ('mucha_cantidad', 'Mucha cantidad'), ('se_hizo_retiro', 'Se hizo retiro'), ('contiene_residuos_peligrosos', 'Contiene residuos peligrosos'), ('otros', 'Otros')], max_length=500, verbose_name='Mezclados')),
                ('mezclados_otras_observaciones', models.CharField(max_length=500, verbose_name='Mezclados')),
                ('peligrosos', models.CharField(choices=[('aplica', 'Aplica'), ('no_aplica', 'No Aplica')], max_length=200, verbose_name='Peligrosos')),
                ('punto_de_acopio', models.CharField(max_length=200, verbose_name='Punto de acopio')),
                ('peligrosos_observaciones', models.CharField(choices=[('tanques_vacios', 'Tanques vacíos'), ('tanques_llenos', 'Tanques llenos'), ('falta_cajon_antiderrame', 'Falta cajón antiderrame'), ('falta_orden', 'Falta orden'), ('contiene_residuos_que_no_corresponden', 'Contiene residuos que no corresponden'), ('otro', 'Otro')], max_length=500, verbose_name='Peligrosos')),
                ('peligrosos_otras_observaciones', models.CharField(max_length=500, verbose_name='Peligrosos')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='obras.obra')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='tecnicos.tecnico')),
            ],
        ),
    ]
