# Generated by Django 5.1.5 on 2025-02-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularios',
            name='madera_observaciones',
            field=models.CharField(choices=[('a_granel', 'A granel'), ('mala_organizacion', 'Mala organización'), ('mucha_cantidad', 'Mucha cantidad'), ('se_esta_reutilizando_en_obra', 'Se está reutilizando en obra'), ('contaminado_con_aceite_pintura_pegamento', 'Contaminado con aceite, pintura, pegamento'), ('otro', 'Otro')], default='a_granel', max_length=500, verbose_name='Madera'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formularios',
            name='madera',
            field=models.CharField(choices=[('aplica', 'Aplica'), ('no_aplica', 'No Aplica')], max_length=200, verbose_name='Madera'),
        ),
    ]
