# Generated by Django 5.1.6 on 2025-03-03 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_formularios_madera_observaciones_and_more'),
        ('obras', '0006_remove_obra_localidad_barrio_and_more'),
        ('tecnicos', '0004_tecnico_usuario_alter_tecnico_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularios',
            name='acciones_tomadas',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='escombro_limpio_observaciones',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='escombro_limpio_otras_observaciones',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='madera_observaciones',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='madera_otras_observaciones',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='metales_observaciones',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='metales_otras_observaciones',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='mezclados_observaciones',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='mezclados_otras_observaciones',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='mezclados_separaciones',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='otras_observaciones',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='papel_y_carton_observaciones',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='papel_y_carton_otras_observaciones',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='peligrosos_observaciones',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='peligrosos_otras_observaciones',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='plastico_observaciones',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='plastico_otras_observaciones',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='punto_de_acopio',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='punto_de_acopio_estado_contenedor',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='punto_de_acopio_estructura',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='punto_de_acopio_observaciones',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='punto_de_acopio_señaletica',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='punto_de_acopio_tipo_contenedor',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='punto_de_acopio_ubicacion',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='punto_limpio_estado_contenedor_pisos',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='punto_limpio_estructura_pisos',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='punto_limpio_observaciones_pisos',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='punto_limpio_pisos',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='punto_limpio_señaletica_pisos',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='punto_limpio_tipo_contenedor_pisos',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='punto_limpio_ubicacion_pisos',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='puntos_limpios_por_pisos',
        ),
        migrations.AlterField(
            model_name='formularios',
            name='escombro_limpio',
            field=models.CharField(blank=True, choices=[('aplica', 'Aplica'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=200, null=True, verbose_name='Escombro limpio'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='limpieza_general_en_pisos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Limpieza general en pisos'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='limpieza_general_en_terreno',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Limpieza general en terreno'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='limpieza_general_observaciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Limpieza observaciones'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='logistica_de_obra',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Logística de obra'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='logistica_de_obra_observaciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Logística observaciones'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='madera',
            field=models.CharField(blank=True, choices=[('aplica', 'Aplica'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=200, null=True, verbose_name='Madera'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='metales',
            field=models.CharField(blank=True, choices=[('aplica', 'Aplica'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=200, null=True, verbose_name='Metales'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='mezclados',
            field=models.CharField(blank=True, choices=[('aplica', 'Aplica'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=200, null=True, verbose_name='Mezclados'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='motivo_de_visita',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo de visita'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='obras.obra'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='papel_y_carton',
            field=models.CharField(blank=True, choices=[('aplica', 'Aplica'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=200, null=True, verbose_name='Papel y cartón'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='participante_jornal_ambiental',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Participante jornal ambiental'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='participante_observaciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Participante observaciones'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='participante_oficina_tecnica',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Participante oficina técnica'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='participante_operario',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Participante operario'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='peligrosos',
            field=models.CharField(blank=True, choices=[('aplica', 'Aplica'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=200, null=True, verbose_name='Peligrosos'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='plastico',
            field=models.CharField(blank=True, choices=[('aplica', 'Aplica'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=200, null=True, verbose_name='Plástico'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='punto_limpio',
            field=models.CharField(blank=True, choices=[('si_hay', 'Sí Hay'), ('no_hay', 'No Hay')], default='no_hay', max_length=200, null=True, verbose_name='Punto limpio'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='punto_limpio_estado_contenedor',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Punto limpio estado'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='punto_limpio_estructura',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Punto limpio estructura'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='punto_limpio_observaciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Punto limpio observaciones'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='punto_limpio_señaletica',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Punto limpio señalética'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='punto_limpio_tipo_contenedor',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Punto limpio tipo contenedor'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='punto_limpio_ubicacion',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Punto limpio ubicación'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='tecnicos.tecnico'),
        ),
    ]
