# Generated by Django 5.1.6 on 2025-03-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_remove_formularios_acciones_tomadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularios',
            name='otras_observaciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Otras observaciones'),
        ),
    ]
