# Generated by Django 5.1.6 on 2025-03-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_formularios_acciones_tomadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularios',
            name='escombro_limpio',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=200, null=True, verbose_name='Escombro limpio'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='madera',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=200, null=True, verbose_name='Madera'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='metales',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=200, null=True, verbose_name='Metales'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='mezclados',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=200, null=True, verbose_name='Mezclados'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='papel_y_carton',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=200, null=True, verbose_name='Papel y cartón'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='peligrosos',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=200, null=True, verbose_name='Peligrosos'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='plastico',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=200, null=True, verbose_name='Plástico'),
        ),
    ]
