# Generated by Django 5.1.6 on 2025-03-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0006_alter_formularios_escombro_limpio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularios',
            name='peligrosos',
        ),
        migrations.AddField(
            model_name='formularios',
            name='acopioContenedores',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Acopio contenedores'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='escombro_checks',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Escombro checks'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='escombro_observaciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Escombro observaciones'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='escombro_otro_texto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Escombro otro texto'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='gridSelection',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Grid selection'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='grilla',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Grilla'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='grillaPuntosLimpiosPisos',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Grilla puntos limpios por pisos'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='madera_observaciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Madera observaciones'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='madera_opciones',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Madera opciones'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='madera_otro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Madera otro'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='metales_observaciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Metales observaciones'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='metales_opciones',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Metales opciones'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='metales_otro_texto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Metales otro texto'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='mezclados_observaciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mezclados observaciones'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='mezclados_opciones',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Mezclados opciones'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='mezclados_otro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mezclados otro'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='papel_carton_observaciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Papel cartón observaciones'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='papel_carton_opciones',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Papel cartón opciones'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='papel_carton_otro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Papel cartón otro'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='plastico_observaciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Plástico observaciones'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='plastico_opciones',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Plástico opciones'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='plastico_otro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Plástico otro'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='puntoAcopio',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=200, null=True, verbose_name='Punto Acopio'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='puntoAcopioGrid',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Punto Acopio Grid'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='puntoAcopioObservaciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Punto Acopio Observaciones'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='puntoAcopioOpciones',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Punto Acopio Opciones'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='puntoAcopioOtro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Punto Acopio Otro'),
        ),
        migrations.AddField(
            model_name='formularios',
            name='puntos_limpios_por_pisos',
            field=models.CharField(blank=True, default='No hay', max_length=200, null=True, verbose_name='Puntos limpios por pisos'),
        ),
    ]
