# Generated by Django 5.1.6 on 2025-03-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0007_remove_formularios_peligrosos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularios',
            name='papel_y_carton',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('No aplica', 'No aplica')], default='no_aplica', max_length=200, null=True, verbose_name='Papel y cartón'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='plastico',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('No Aplica', 'No Aplica')], default='no_aplica', max_length=200, null=True, verbose_name='Plástico'),
        ),
    ]
