# Generated by Django 5.1.6 on 2025-03-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0009_alter_formularios_papel_y_carton_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularios',
            name='escombro_limpio',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('No Aplica', 'No Aplica')], default='No Aplica', max_length=200, null=True, verbose_name='Escombro limpio'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='madera',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('No Aplica', 'No Aplica')], default='No Aplica', max_length=200, null=True, verbose_name='Madera'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='metales',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('No Aplica', 'No Aplica')], default='No Aplica', max_length=200, null=True, verbose_name='Metales'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='mezclados',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('No Aplica', 'No Aplica')], default='No Aplica', max_length=200, null=True, verbose_name='Mezclados'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='papel_y_carton',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('No Aplica', 'No Aplica')], default='No Aplica', max_length=200, null=True, verbose_name='Papel y cartón'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='plastico',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('No Aplica', 'No Aplica')], default='No Aplica', max_length=200, null=True, verbose_name='Plástico'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='puntoAcopio',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('No Aplica', 'No Aplica')], default='No Aplica', max_length=200, null=True, verbose_name='Punto Acopio'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='punto_limpio',
            field=models.CharField(blank=True, choices=[('Hay', 'Hay'), ('No Hay', 'No Hay')], default='No Hay', max_length=200, null=True, verbose_name='Punto limpio'),
        ),
    ]
