# Generated by Django 5.1.6 on 2025-03-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0010_alter_formularios_escombro_limpio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularios',
            name='punto_limpio_edificio_observaciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Punto limpio Edificio observaciones'),
        ),
    ]
