# Generated by Django 5.1.6 on 2025-03-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0011_formularios_punto_limpio_edificio_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularios',
            name='punto_limpio_señaletica',
        ),
        migrations.AddField(
            model_name='formularios',
            name='punto_limpio_senaletica',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Punto limpio senalética'),
        ),
    ]
