# Generated by Django 5.1.6 on 2025-03-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0012_remove_formularios_punto_limpio_señaletica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularios',
            name='papel_carton_observaciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Papel carton observaciones'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='papel_carton_opciones',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Papel carton opciones'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='papel_carton_otro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Papel carton otro'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='papel_y_carton',
            field=models.CharField(blank=True, choices=[('Aplica', 'Aplica'), ('No Aplica', 'No Aplica')], default='No Aplica', max_length=200, null=True, verbose_name='Papel y carton'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='punto_limpio_ubicacion',
            field=models.CharField(blank=True, default='No especificado', max_length=200, null=True, verbose_name='Punto limpio ubicacion'),
        ),
    ]
